export enum ErrorCode {
    VALIDATION_ERROR = "VALIDATION_ERROR",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
    TOKEN_EXPIRED = "TOKEN_EXPIRED",
    LOGIN_REQUIRED = "LOGIN_REQUIRED",
    UNAUTHORIZED = "UNAUTHORIZED",
    ACCOUNT_BLOCKED = "ACCOUNT_BLOCKED",
    FORBIDDEN = "FORBIDDEN",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    BAD_REQUEST = "BAD_REQUEST"
}
